api:
  build: .
  ports:
   - "80:80"
  links:
   - rabbitmq
  command: faafo-api
worker:
  build: .
  links:
   - rabbitmq
   - api
  command: faafo-worker
rabbitmq:
  image: rabbitmq:3
  ports:
   - "5672:5672"
